"""Crear tabla de comprobantes de multas

Revision ID: 02c640609da2
Revises: b5b646a7549b
Create Date: 2026-09-08 19:18:44.451938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c640609da2'
down_revision: Union[str, Sequence[str], None] = 'b5b646a7549b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobantes_multas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multa_id', sa.Integer(), nullable=False),
    sa.Column('num_cuenta', sa.String(length=13), nullable=False),
    sa.Column('num_referencia', sa.String(length=100), nullable=False),
    sa.Column('ruta_pdf', sa.String(length=255), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_aportacion.id'], ),
    sa.ForeignKeyConstraint(['multa_id'], ['multas.id'], ),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobantes_multas_id'), 'comprobantes_multas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comprobantes_multas_id'), table_name='comprobantes_multas')
    op.drop_table('comprobantes_multas')
    # ### end Alembic commands ###
