"""quitar columna activo de perfiles_becarios

Revision ID: 140decd49b9c
Revises: 9fc6e4ec1d0c
Create Date: 2026-09-13 20:36:23.110888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140decd49b9c'
down_revision: Union[str, Sequence[str], None] = '9fc6e4ec1d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles_becarios', 'activo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
