"""agregar columna activo a carreras

Revision ID: 1b86486d6bf7
Revises: a25b7e1f0a2b
Create Date: 2026-09-13 18:09:35.886343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b86486d6bf7'
down_revision: Union[str, Sequence[str], None] = 'a25b7e1f0a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'carreras', 
        sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carreras', 'activo')
    # ### end Alembic commands ###
