"""crear tablas aportacion y estados aportacion

Revision ID: 2dacc15bb8bc
Revises: a89918c34dd2
Create Date: 2026-09-08 15:11:18.557959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dacc15bb8bc'
down_revision: Union[str, Sequence[str], None] = 'a89918c34dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_aportacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_aportacion_id'), 'estados_aportacion', ['id'], unique=False)
    op.create_index(op.f('ix_estados_aportacion_nombre_estado'), 'estados_aportacion', ['nombre_estado'], unique=True)
    op.create_table('aportaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_cuenta', sa.String(), nullable=False),
    sa.Column('num_referencia', sa.String(), nullable=False),
    sa.Column('ruta_pdf', sa.String(), nullable=False),
    sa.Column('estado_aportacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado_aportacion_id'], ['estados_aportacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportaciones_id'), 'aportaciones', ['id'], unique=False)
    op.create_index(op.f('ix_aportaciones_num_referencia'), 'aportaciones', ['num_referencia'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aportaciones_num_referencia'), table_name='aportaciones')
    op.drop_index(op.f('ix_aportaciones_id'), table_name='aportaciones')
    op.drop_table('aportaciones')
    op.drop_index(op.f('ix_estados_aportacion_nombre_estado'), table_name='estados_aportacion')
    op.drop_index(op.f('ix_estados_aportacion_id'), table_name='estados_aportacion')
    op.drop_table('estados_aportacion')
    # ### end Alembic commands ###
