"""cambios tabla aportacion

Revision ID: 611f7bb374c5
Revises: 2dacc15bb8bc
Create Date: 2026-09-08 17:54:21.982708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611f7bb374c5'
down_revision: Union[str, Sequence[str], None] = '2dacc15bb8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aportaciones', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('aportaciones', sa.Column('meses_aprobados', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aportaciones', 'meses_aprobados')
    op.drop_column('aportaciones', 'descripcion')
    # ### end Alembic commands ###
