"""sprint3_completo

Revision ID: 9bf820f154de
Revises: e2d4fba8a48e
Create Date: 2026-08-24 12:03:55.274121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf820f154de'
down_revision: Union[str, Sequence[str], None] = 'e2d4fba8a48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_quota',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('correos_enviados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('estados_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_actividad_id'), 'estados_actividad', ['id'], unique=False)
    op.create_table('estados_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_asistencia_id'), 'estados_asistencia', ['id'], unique=False)
    op.create_table('pin_intentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_intentos_id'), 'pin_intentos', ['id'], unique=False)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.Column('fecha_actividad', sa.Date(), nullable=True),
    sa.Column('horas_asignar', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('cupos', sa.Integer(), nullable=True),
    sa.Column('estado_actividad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_actividad_id'], ['estados_actividad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('num_cuenta', sa.String(), nullable=True),
    sa.Column('check_in', sa.Boolean(), nullable=True),
    sa.Column('check_out', sa.Boolean(), nullable=True),
    sa.Column('estado_asistencia_id', sa.Integer(), nullable=True),
    sa.Column('horas_registradas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['estado_asistencia_id'], ['estados_asistencia.id'], ),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_cuenta', sa.String(length=13), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_unique_constraint('uq_usuarios_correo_institucional', 'usuarios', ['correo_institucional'])
    op.create_table('pines_activacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correo'], ['usuarios.correo_institucional'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pines_activacion_id'), 'pines_activacion', ['id'], unique=False)
    op.alter_column('roles', 'nombre_rol',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'usuarios', ['correo_institucional'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('usuarios', 'password_hash')
    op.alter_column('roles', 'nombre_rol',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_index(op.f('ix_pines_activacion_id'), table_name='pines_activacion')
    op.drop_table('pines_activacion')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_pin_intentos_id'), table_name='pin_intentos')
    op.drop_table('pin_intentos')
    op.drop_index(op.f('ix_estados_asistencia_id'), table_name='estados_asistencia')
    op.drop_table('estados_asistencia')
    op.drop_index(op.f('ix_estados_actividad_id'), table_name='estados_actividad')
    op.drop_table('estados_actividad')
    op.drop_table('email_quota')
    # ### end Alembic commands ###
