"""agregar columna activo a perfiles_becarios

Revision ID: 9fc6e4ec1d0c
Revises: 1b86486d6bf7
Create Date: 2026-09-13 19:50:50.757561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc6e4ec1d0c'
down_revision: Union[str, Sequence[str], None] = '1b86486d6bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'perfiles_becarios', 
        sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles_becarios', 'activo')
    # ### end Alembic commands ###
