"""agregar onupdate cascade en pines_activacion

Revision ID: a25b7e1f0a2b
Revises: 02c640609da2
Create Date: 2026-09-09 17:34:59.172584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25b7e1f0a2b'
down_revision: Union[str, Sequence[str], None] = '02c640609da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pines_activacion_correo_fkey'), 'pines_activacion', type_='foreignkey')
    op.create_foreign_key(None, 'pines_activacion', 'usuarios', ['correo'], ['correo_institucional'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pines_activacion', type_='foreignkey')
    op.create_foreign_key(op.f('pines_activacion_correo_fkey'), 'pines_activacion', 'usuarios', ['correo'], ['correo_institucional'])
    # ### end Alembic commands ###
