"""email_quota

Revision ID: a3ae97c56751
Revises: eed41d5b87e2
Create Date: 2026-08-24 11:20:58.301983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ae97c56751'
down_revision: Union[str, Sequence[str], None] = 'eed41d5b87e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_quota',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('correos_enviados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fecha')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_quota')
    # ### end Alembic commands ###
