"""crear tabla multa

Revision ID: a89918c34dd2
Revises: cfeedb1f5c93
Create Date: 2026-08-27 16:54:05.697214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89918c34dd2'
down_revision: Union[str, Sequence[str], None] = 'cfeedb1f5c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_cuenta', sa.String(length=13), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=True),
    sa.Column('fecha_multa', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multas_id'), 'multas', ['id'], unique=False)
    op.alter_column('actividades', 'token_entrada',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('actividades', 'token_salida',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actividades', 'token_salida',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('actividades', 'token_entrada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_multas_id'), table_name='multas')
    op.drop_table('multas')
    # ### end Alembic commands ###
