"""estructura_sprint2

Revision ID: aaab4d6bd9a7
Revises: e2d4fba8a48e
Create Date: 2026-08-20 13:57:08.572398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaab4d6bd9a7'
down_revision: Union[str, Sequence[str], None] = 'e2d4fba8a48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_quota')
    op.drop_table('actividades')
    op.drop_table('estados_asistencia')
    op.drop_table('tipos_pago')
    op.drop_table('pagos')
    op.drop_table('multas')
    op.drop_table('asistencias')
    op.drop_table('estados_actividad')
    op.drop_table('estados_pago')
    op.alter_column('carreras', 'nombre_carrera',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_index(op.f('ix_estados_beca_id'), 'estados_beca', ['id'], unique=False)
    op.alter_column('perfiles_becarios', 'num_cuenta',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.create_index(op.f('ix_perfiles_becarios_id'), 'perfiles_becarios', ['id'], unique=False)
    op.drop_constraint(op.f('perfiles_becarios_estado_beca_id_fkey'), 'perfiles_becarios', type_='foreignkey')
    op.drop_constraint(op.f('perfiles_becarios_num_cuenta_fkey'), 'perfiles_becarios', type_='foreignkey')
    op.create_foreign_key(None, 'perfiles_becarios', 'estados_beca', ['estado_beca_id'], ['id'])
    op.create_foreign_key(None, 'perfiles_becarios', 'usuarios', ['num_cuenta'], ['num_cuenta'])
    op.alter_column('pin_intentos', 'correo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('pin_intentos_correo_fecha_key'), 'pin_intentos', type_='unique')
    op.create_index(op.f('ix_pin_intentos_id'), 'pin_intentos', ['id'], unique=False)
    op.alter_column('pines_activacion', 'correo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('pines_activacion', 'pin_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_pines_activacion_id'), 'pines_activacion', ['id'], unique=False)
    op.alter_column('roles', 'nombre_rol',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('usuarios', 'num_cuenta',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=13),
               existing_nullable=False)
    op.alter_column('usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'correo_personal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'correo_institucional',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_usuarios_num_cuenta'), 'usuarios', ['num_cuenta'], unique=False)
    op.drop_constraint(op.f('usuarios_carrera_id_fkey'), 'usuarios', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_rol_id_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'carreras', ['carrera_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id'])
    op.drop_column('usuarios', 'anio_nacimiento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('anio_nacimiento', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_rol_id_fkey'), 'usuarios', 'roles', ['rol_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('usuarios_carrera_id_fkey'), 'usuarios', 'carreras', ['carrera_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_usuarios_num_cuenta'), table_name='usuarios')
    op.alter_column('usuarios', 'correo_institucional',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'correo_personal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuarios', 'num_cuenta',
               existing_type=sa.String(length=13),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.alter_column('roles', 'nombre_rol',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_pines_activacion_id'), table_name='pines_activacion')
    op.alter_column('pines_activacion', 'pin_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('pines_activacion', 'correo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_pin_intentos_id'), table_name='pin_intentos')
    op.create_unique_constraint(op.f('pin_intentos_correo_fecha_key'), 'pin_intentos', ['correo', 'fecha'], postgresql_nulls_not_distinct=False)
    op.alter_column('pin_intentos', 'correo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'perfiles_becarios', type_='foreignkey')
    op.drop_constraint(None, 'perfiles_becarios', type_='foreignkey')
    op.create_foreign_key(op.f('perfiles_becarios_num_cuenta_fkey'), 'perfiles_becarios', 'usuarios', ['num_cuenta'], ['num_cuenta'], ondelete='SET NULL')
    op.create_foreign_key(op.f('perfiles_becarios_estado_beca_id_fkey'), 'perfiles_becarios', 'estados_beca', ['estado_beca_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_perfiles_becarios_id'), table_name='perfiles_becarios')
    op.alter_column('perfiles_becarios', 'num_cuenta',
               existing_type=sa.String(length=13),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_estados_beca_id'), table_name='estados_beca')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.alter_column('carreras', 'nombre_carrera',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('estados_pago',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_estado', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('estados_pago_pkey'))
    )
    op.create_table('estados_actividad',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_estado', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('estados_actividad_pkey'))
    )
    op.create_table('asistencias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_cuenta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('check_out', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('estado_asistencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('horas_registradas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], name=op.f('asistencias_actividad_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_asistencia_id'], ['estados_asistencia.id'], name=op.f('asistencias_estado_asistencia_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], name=op.f('asistencias_num_cuenta_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('asistencias_pkey'))
    )
    op.create_table('multas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_cuenta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_generada', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('es_pagada', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], name=op.f('multas_num_cuenta_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('multas_pkey'))
    )
    op.create_table('pagos',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_cuenta', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('monto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('estado_pago_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_pago_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estado_pago_id'], ['estados_pago.id'], name=op.f('pagos_estado_pago_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], name=op.f('pagos_num_cuenta_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_pago_id'], ['tipos_pago.id'], name=op.f('pagos_tipo_pago_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pagos_pkey'))
    )
    op.create_table('tipos_pago',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pago_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tipos_pago_pkey'))
    )
    op.create_table('estados_asistencia',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_estado', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('estados_asistencia_pkey'))
    )
    op.create_table('actividades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ubicacion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_actividad', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('horas_asignar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('hora_final', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('cupos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado_actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estado_actividad_id'], ['estados_actividad.id'], name=op.f('actividades_estado_actividad_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('actividades_pkey'))
    )
    op.create_table('email_quota',
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('correos_enviados', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fecha', name=op.f('email_quota_pkey'))
    )
    # ### end Alembic commands ###
