"""cambios_sprint4

Revision ID: cfeedb1f5c93
Revises: 9bf820f154de
Create Date: 2026-08-27 15:33:51.203710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfeedb1f5c93'
down_revision: Union[str, Sequence[str], None] = '9bf820f154de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('token_entrada', sa.String(), nullable=True))
    op.add_column('actividades', sa.Column('token_salida', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades', 'token_salida')
    op.drop_column('actividades', 'token_entrada')
    # ### end Alembic commands ###
