"""crear_estructura_inicial_asebep

Revision ID: e2d4fba8a48e
Revises: 
Create Date: 2026-06-13 22:11:15.409325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d4fba8a48e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_carrera', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_table('estados_beca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_beca_id'), 'estados_beca', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('num_cuenta', sa.String(length=13), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=20), nullable=True),
    sa.Column('correo_personal', sa.String(), nullable=True),
    sa.Column('correo_intitucional', sa.String(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('num_cuenta')
    )
    op.create_index(op.f('ix_usuarios_num_cuenta'), 'usuarios', ['num_cuenta'], unique=False)
    op.create_table('perfiles_becarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_cuenta', sa.String(length=13), nullable=True),
    sa.Column('periodo_inicio', sa.String(length=10), nullable=True),
    sa.Column('anio_inicio', sa.Integer(), nullable=True),
    sa.Column('mes_inicio', sa.Integer(), nullable=True),
    sa.Column('horas_acumuladas', sa.Integer(), nullable=True),
    sa.Column('estado_beca_id', sa.Integer(), nullable=True),
    sa.Column('fecha_fin_beca', sa.Date(), nullable=True),
    sa.Column('monto_acumulado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_beca_id'], ['estados_beca.id'], ),
    sa.ForeignKeyConstraint(['num_cuenta'], ['usuarios.num_cuenta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfiles_becarios_id'), 'perfiles_becarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfiles_becarios_id'), table_name='perfiles_becarios')
    op.drop_table('perfiles_becarios')
    op.drop_index(op.f('ix_usuarios_num_cuenta'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_estados_beca_id'), table_name='estados_beca')
    op.drop_table('estados_beca')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
