from .becario import Becario
from .carrera import Carrera
from .estado_beca import EstadoBeca
from .rol import Rol
from .usuario import Usuario
from .pin_activacion import PinActivacion
from .pin_intentos import PinIntentos
from .actividad import Actividad
from .estado_actividad import EstadoActividad
from .asistencia import Asistencia
from .estado_asistencia import EstadoAsistencia
from .pagos import Pago
from .email_quota import EmailQuota
from .multa import Multa